### ISSUE TITLE
'SIgn In' tab error main.ts:61  TypeError: o.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by Algocrat** [NetCoreTemplates/vue-spa#1]
Created a new project 
Build
Debug
Navigate to Sign In
Error shows up

main.ts:61  TypeError: o.hasOwnProperty is not a function
    at omit (servicestack-client.mjs:2260:15)
    at Proxy.<anonymous> (servicestack-vue.mjs:3479:17)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6020:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6151:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6161:5)
    at mountComponent (runtime-core.esm-bundler.js:5929:7)
    at processComponent (runtime-core.esm-bundler.js:5883:9)
    at patch (runtime-core.esm-bundler.js:5351:11)

**Comment by mythz** [comment]
Should now be fixed after upgrading deps or creating a new project from the vue-spa template.
